openapi: 3.0.0
info:
  title: Alagar server API
  version: 1.0.0
security:
- Authorization: []
tags:
- name: Auth
  description: Operations related to user authentication
- name: User
  description: "Operations related to user management"
- name: Sensor
  description: Operations related to sensor data
- name: Report
  description: Operations for generating reports
- name: Auto
  description: Operations related to Auto management
- name: Wheel
  description: Operations related to wheel management
paths:
  /login:
    post:
      tags:
      - Auth
      summary: User login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
      security: []
  /refresh:
    post:
      tags:
      - Auth
      summary: Refresh access token
      responses:
        "200":
          description: Successful token refresh
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
  /user:
    put:
      tags:
      - User
      summary: Update user password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePassword'
        required: true
      responses:
        "200":
          description: Successful password update
    post:
      tags:
      - User
      summary: User registration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
        required: true
      responses:
        "200":
          description: Successful registration
      security: []
    get:
      tags:
      - User
      summary: Get user details
      parameters:
      - name: id
        in: query
        required: true
        schema: 
          type: string
      responses:
        "200":
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetails'
  /sensor:
    get:
      tags:
        - Sensor
      summary: Get sensors by car ID
      parameters:
        - name: car_id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Sensor data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorData'
    post:
      tags:
        - Sensor
      summary: Register a new sensor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SensorRegistration'
        required: true
      responses:
        "201":
          description: Successful sensor registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorData'
      security: []
    put:
      tags:
        - Sensor
      summary: Update an existing sensor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SensorRegistration'
        required: true
      responses:
        "200":
          description: Successful sensor update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorData'
      security: []
  /report:
    get:
      tags:
      - Report
      summary: Generate report
      parameters:
      - name: userId
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Report in XLSX format
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                $ref: '#/components/schemas/ReportResponse'
  /auto/list:
    get:
      tags:
        - Auto
      summary: Get list of Autos
      parameters:
        - name: offset
          in: query
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: List of Autos
          content:
            application/json:
              schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/AutoResponse'
                    
  /auto:
    get:
      tags:
        - Auto
      summary: Get a single Auto by ID
      parameters:
        - name: car_id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Vehicle details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoResponse'
    post:
      tags:
      - Auto
      summary: Register a Auto
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoRegistration'
        required: true
      responses:
        "200":
          description: Successful Auto registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoResponse'
  /wheels:
    put:
      tags:
      - Wheel
      summary: Update wheel data
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WheelChange'
        required: true
      responses:
        "200":
          description: Successful wheel update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WheelResponse'
    post:
      tags:
      - Wheel
      summary: Register a wheel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WheelRegistration'
        required: true
      responses:
        "200":
          description: Successful wheel registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WheelResponse'
      security:
      - Authorization: []
    get:
      tags:
      - Wheel
      summary: Get wheel data
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Wheel data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WheelResponse'
  /brackeges:
    get:
      tags:
        - Breakage
      summary: Get breakages by car ID
      parameters:
        - name: car_id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Breakage data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BreakageResponse'
    post:
      tags:
        - Breakage
      summary: Register a new breakage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BreakageRegistration'
        required: true
      responses:
        "201":
          description: Successful breakage registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BreakageResponse'
      security: []
components:
  schemas:
    LoginRequest:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    TokenResponse:
      required:
      - accessToken
      - refreshToken
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
      example:
        accessToken: accessToken
        refreshToken: refreshToken
    UserRegistration:
      required:
      - email
      - firstName
      - lastName
      - password
      - phone
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        phone:
          type: string
        email:
          type: string
        timeZone:
          type: string
        inn:
          type: string
        password:
          type: string
    UserDetails:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        phone:
          type: string
        email:
          type: string
        timeZone:
          type: string
        inn:
          type: string
        password:
          type: string
      example:
        firstName: firstName
        lastName: lastName
        password: password
        phone: phone
        inn: inn
        timeZone: timeZone
        middleName: middleName
        email: email
    UpdatePassword:
      required:
      - newPassword
      type: object
      properties:
        newPassword:
          type: string
    ReportResponse:
      type: string
      format: byte
    AutoRegistration:
      required:
      - axleCount
      - brand
      - companyInn
      - deviceId
      - stateNumber
      - uniqueId
      - AutoType
      type: object
      properties:
        companyInn:
          type: string
        deviceId:
          type: string
        uniqueId:
          type: string
        AutoType:
          type: string
        stateNumber:
          type: string
        brand:
          type: string
        axleCount:
          type: integer
    AutoResponse:
      type: object
      properties:
        id:
          type: string
        companyInn:
          type: string
        deviceId:
          type: string
        uniqueId:
          type: string
        AutoType:
          type: string
        stateNumber:
          type: string
        brand:
          type: string
        axleCount:
          type: integer
      example:
        stateNumber: stateNumber
        companyInn: companyInn
        axleCount: 0
        id: id
        deviceId: deviceId
        brand: brand
        uniqueId: uniqueId
        AutoType: AutoType
    WheelRegistration:
      required:
      - axleNumber
      - maxPressure
      - maxTemperature
      - mileage
      - minPressure
      - minTemperature
      - sensorNumber
      - tireBrand
      - tireCost
      - tireModel
      - tireSize
      - AutoId
      - wheelPosition
      type: object
      properties:
        AutoId:
          type: string
        axleNumber:
          type: integer
        wheelPosition:
          type: integer
        sensorNumber:
          type: string
        tireSize:
          type: string
        tireCost:
          type: number
        tireBrand:
          type: string
        tireModel:
          type: string
        minPressure:
          type: number
        mileage:
          type: number
        maxPressure:
          type: number
        minTemperature:
          type: number
        maxTemperature:
          type: number
    WheelChange:
      required:
      - id
      - axleNumber
      - maxPressure
      - maxTemperature
      - mileage
      - minPressure
      - minTemperature
      - sensorNumber
      - tireBrand
      - tireCost
      - tireModel
      - tireSize
      - AutoId
      - wheelPosition
      type: object
      properties:
        id:
          type: string
        AutoId:
          type: string
        axleNumber:
          type: integer
        wheelPosition:
          type: integer
        sensorNumber:
          type: string
        tireSize:
          type: string
        tireCost:
          type: number
        tireBrand:
          type: string
        tireModel:
          type: string
        minPressure:
          type: number
        mileage:
          type: number
        maxPressure:
          type: number
        minTemperature:
          type: number
        maxTemperature:
          type: number
    WheelResponse:
      type: object
      properties:
        id:
          type: string
        AutoId:
          type: string
        axleNumber:
          type: integer
        wheelPosition:
          type: integer
        sensorNumber:
          type: string
        tireSize:
          type: string
        tireCost:
          type: number
        tireBrand:
          type: string
        tireModel:
          type: string
        minPressure:
          type: number
        mileage:
          type: number
        maxPressure:
          type: number
        minTemperature:
          type: number
        maxTemperature:
          type: number
      example:
        axleNumber: 0
        maxTemperature: 9.301444243932575517419536481611430644989013671875
        tireBrand: tireBrand
        tireModel: tireModel
        minTemperature: 7.061401241503109105224211816675961017608642578125
        wheelPosition: 6
        minPressure: 5.962133916683182377482808078639209270477294921875
        sensorNumber: sensorNumber
        maxPressure: 2.3021358869347654518833223846741020679473876953125
        id: id
        AutoId: AutoId
        tireCost: 1.46581298050294517310021547018550336360931396484375
        tireSize: tireSize
        mileage: 5.6373766566333287642009963747113943099975585937
    SensorData:
      type: object
      properties:
        position:
          type: integer
        pressure:
          type: number
        temperature:
          type: number
        time:
          type: string
    BreakageResponse:
      type: object
      properties:
        id:
          type: string
        stateNumber:
          type: string
        type:
          type: string
        description:
          type: string
        datetime:
          type: string
          format: date-tim
    BreakageRegistration:
      type: object
      properties:
        stateNumber:
          type: string
        type:
          type: string
        description:
          type: string
        datetime:
          type: string
          format: date-time
    SensorRegistration:
      type: object
      properties:
        stateNumber:
          type: string
        countAxis:
          type: integer
        position:
          type: integer
        pressure:
          type: number
        temperature:
          type: number
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT